# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e4a7bb29b4fbdf1f90a578e51f03e190974133741798e84ff6cc714cb1600618ac4c5967dc64d60f43c7a67da8528d342d346c1fbd8514c5e23359573bf4697

test:
  secret_key_base: 11818face25408ad5ed2d32e49941182aa35926dd3c90c6ab6af24639370df6b9a98a3dc70d9a45491f3e737047dac827cf6042cb1ba34e4eb85d6cb5be686dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
