# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user = User.create(email: 'garrettstott@gmail.com', password: 'password', password_confirmation: 'password', first_name: 'Garrett', last_name: 'Stott', bio: 'Read This')

Post.create(title: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas lobortis bibendum dolor, in commodo risus ultrices id. Vestibulum luctus dictum tortor, sit amet pretium ligula facilisis eu. Nullam interdum neque sit amet mi ornare, in scelerisque nibh ultrices. Donec eleifend eros ac ipsum commodo, et consectetur dui cursus. Integer in volutpat metus. Maecenas fermentum et ante sed luctus. Mauris felis diam, blandit at turpis sit amet, lacinia ultricies ex. Nunc massa quam, consectetur ac imperdiet nec, cursus ac neque. Nunc bibendum, nisi vitae convallis venenatis, felis est accumsan risus, vel gravida orci nibh vel purus. Vestibulum tempus vitae nisl eget vestibulum. Suspendisse quis est eu est placerat posuere vitae ac ante. Curabitur eu elit ligula. Curabitur ultricies interdum mauris sodales cursus. Vestibulum auctor velit et sapien vulputate consectetur.

Integer non interdum massa. In vitae vulputate dui. Etiam faucibus, sem et malesuada efficitur, tellus ipsum eleifend tellus, in dictum ligula dui ut lorem. Proin ultrices sit amet quam sed accumsan. Quisque vitae velit nec diam semper aliquet. In interdum odio id dui egestas, ac accumsan nulla maximus. Duis vel ligula vitae mi maximus pulvinar id ut arcu. Donec metus tellus, feugiat at felis in, interdum pulvinar ante. Proin eu laoreet lacus. Donec ut tempor arcu. Ut at tellus finibus est tempor rhoncus in tristique ex. Integer in turpis ut turpis egestas malesuada a ut mauris. Aliquam mattis nibh odio, nec dignissim quam pharetra sagittis.

Vestibulum lacinia non lacus nec consequat. Maecenas tempor varius massa ullamcorper varius. Phasellus lobortis in lectus rhoncus rutrum. Maecenas imperdiet dapibus lorem, eu sodales magna. Fusce non placerat mi, eu consequat odio. Ut porta ultrices consectetur. Praesent nunc mauris, iaculis eget lorem ut, mollis feugiat enim. Nunc commodo vitae ante a congue. Integer bibendum luctus lacus eu sollicitudin. Curabitur consequat justo ut nisl feugiat ultrices.

Suspendisse consequat lacus id nisl viverra, vitae ultricies lacus lacinia. Proin aliquam aliquet ipsum, vel tristique nisl rutrum euismod. Sed blandit tellus sit amet lorem viverra hendrerit. Etiam vel ultricies diam. Sed non nunc dapibus turpis ultricies tristique eget vitae enim. Nullam lobortis eros augue. Suspendisse enim ligula, consequat eu tincidunt non, aliquet et ligula. Praesent vestibulum commodo est ut ultrices. Curabitur vel mattis mi. Integer laoreet tempor sem, nec blandit purus mattis id. Praesent tristique lectus gravida, molestie ante vel, congue lectus. Etiam tempus facilisis erat, et semper quam ultricies at. Nunc accumsan eros dolor, non volutpat metus sagittis sit amet. Quisque dignissim tortor quis sem aliquet varius. Nam nec condimentum lacus, sit amet iaculis metus.

Nunc placerat dignissim felis, ac tristique dui cursus eu. Nam suscipit condimentum sem, vitae auctor turpis scelerisque tempus. Mauris hendrerit ligula dictum, convallis purus ut, semper purus. Ut imperdiet erat a mauris convallis fringilla. Nunc convallis nunc ipsum, vel posuere magna imperdiet sed. In hac habitasse platea dictumst. Pellentesque nec urna at nibh consectetur sollicitudin. In hac habitasse platea d', user_id: user.id)
Post.create(title: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas lobortis bibendum dolor, in commodo risus ultrices id. Vestibulum luctus dictum tortor, sit amet pretium ligula facilisis eu. Nullam interdum neque sit amet mi ornare, in scelerisque nibh ultrices. Donec eleifend eros ac ipsum commodo, et consectetur dui cursus. Integer in volutpat metus. Maecenas fermentum et ante sed luctus. Mauris felis diam, blandit at turpis sit amet, lacinia ultricies ex. Nunc massa quam, consectetur ac imperdiet nec, cursus ac neque. Nunc bibendum, nisi vitae convallis venenatis, felis est accumsan risus, vel gravida orci nibh vel purus. Vestibulum tempus vitae nisl eget vestibulum. Suspendisse quis est eu est placerat posuere vitae ac ante. Curabitur eu elit ligula. Curabitur ultricies interdum mauris sodales cursus. Vestibulum auctor velit et sapien vulputate consectetur.

Integer non interdum massa. In vitae vulputate dui. Etiam faucibus, sem et malesuada efficitur, tellus ipsum eleifend tellus, in dictum ligula dui ut lorem. Proin ultrices sit amet quam sed accumsan. Quisque vitae velit nec diam semper aliquet. In interdum odio id dui egestas, ac accumsan nulla maximus. Duis vel ligula vitae mi maximus pulvinar id ut arcu. Donec metus tellus, feugiat at felis in, interdum pulvinar ante. Proin eu laoreet lacus. Donec ut tempor arcu. Ut at tellus finibus est tempor rhoncus in tristique ex. Integer in turpis ut turpis egestas malesuada a ut mauris. Aliquam mattis nibh odio, nec dignissim quam pharetra sagittis.

Vestibulum lacinia non lacus nec consequat. Maecenas tempor varius massa ullamcorper varius. Phasellus lobortis in lectus rhoncus rutrum. Maecenas imperdiet dapibus lorem, eu sodales magna. Fusce non placerat mi, eu consequat odio. Ut porta ultrices consectetur. Praesent nunc mauris, iaculis eget lorem ut, mollis feugiat enim. Nunc commodo vitae ante a congue. Integer bibendum luctus lacus eu sollicitudin. Curabitur consequat justo ut nisl feugiat ultrices.

Suspendisse consequat lacus id nisl viverra, vitae ultricies lacus lacinia. Proin aliquam aliquet ipsum, vel tristique nisl rutrum euismod. Sed blandit tellus sit amet lorem viverra hendrerit. Etiam vel ultricies diam. Sed non nunc dapibus turpis ultricies tristique eget vitae enim. Nullam lobortis eros augue. Suspendisse enim ligula, consequat eu tincidunt non, aliquet et ligula. Praesent vestibulum commodo est ut ultrices. Curabitur vel mattis mi. Integer laoreet tempor sem, nec blandit purus mattis id. Praesent tristique lectus gravida, molestie ante vel, congue lectus. Etiam tempus facilisis erat, et semper quam ultricies at. Nunc accumsan eros dolor, non volutpat metus sagittis sit amet. Quisque dignissim tortor quis sem aliquet varius. Nam nec condimentum lacus, sit amet iaculis metus.

Nunc placerat dignissim felis, ac tristique dui cursus eu. Nam suscipit condimentum sem, vitae auctor turpis scelerisque tempus. Mauris hendrerit ligula dictum, convallis purus ut, semper purus. Ut imperdiet erat a mauris convallis fringilla. Nunc convallis nunc ipsum, vel posuere magna imperdiet sed. In hac habitasse platea dictumst. Pellentesque nec urna at nibh consectetur sollicitudin. In hac habitasse platea d', user_id: user.id)
Post.create(title: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas lobortis bibendum dolor, in commodo risus ultrices id. Vestibulum luctus dictum tortor, sit amet pretium ligula facilisis eu. Nullam interdum neque sit amet mi ornare, in scelerisque nibh ultrices. Donec eleifend eros ac ipsum commodo, et consectetur dui cursus. Integer in volutpat metus. Maecenas fermentum et ante sed luctus. Mauris felis diam, blandit at turpis sit amet, lacinia ultricies ex. Nunc massa quam, consectetur ac imperdiet nec, cursus ac neque. Nunc bibendum, nisi vitae convallis venenatis, felis est accumsan risus, vel gravida orci nibh vel purus. Vestibulum tempus vitae nisl eget vestibulum. Suspendisse quis est eu est placerat posuere vitae ac ante. Curabitur eu elit ligula. Curabitur ultricies interdum mauris sodales cursus. Vestibulum auctor velit et sapien vulputate consectetur.

Integer non interdum massa. In vitae vulputate dui. Etiam faucibus, sem et malesuada efficitur, tellus ipsum eleifend tellus, in dictum ligula dui ut lorem. Proin ultrices sit amet quam sed accumsan. Quisque vitae velit nec diam semper aliquet. In interdum odio id dui egestas, ac accumsan nulla maximus. Duis vel ligula vitae mi maximus pulvinar id ut arcu. Donec metus tellus, feugiat at felis in, interdum pulvinar ante. Proin eu laoreet lacus. Donec ut tempor arcu. Ut at tellus finibus est tempor rhoncus in tristique ex. Integer in turpis ut turpis egestas malesuada a ut mauris. Aliquam mattis nibh odio, nec dignissim quam pharetra sagittis.

Vestibulum lacinia non lacus nec consequat. Maecenas tempor varius massa ullamcorper varius. Phasellus lobortis in lectus rhoncus rutrum. Maecenas imperdiet dapibus lorem, eu sodales magna. Fusce non placerat mi, eu consequat odio. Ut porta ultrices consectetur. Praesent nunc mauris, iaculis eget lorem ut, mollis feugiat enim. Nunc commodo vitae ante a congue. Integer bibendum luctus lacus eu sollicitudin. Curabitur consequat justo ut nisl feugiat ultrices.

Suspendisse consequat lacus id nisl viverra, vitae ultricies lacus lacinia. Proin aliquam aliquet ipsum, vel tristique nisl rutrum euismod. Sed blandit tellus sit amet lorem viverra hendrerit. Etiam vel ultricies diam. Sed non nunc dapibus turpis ultricies tristique eget vitae enim. Nullam lobortis eros augue. Suspendisse enim ligula, consequat eu tincidunt non, aliquet et ligula. Praesent vestibulum commodo est ut ultrices. Curabitur vel mattis mi. Integer laoreet tempor sem, nec blandit purus mattis id. Praesent tristique lectus gravida, molestie ante vel, congue lectus. Etiam tempus facilisis erat, et semper quam ultricies at. Nunc accumsan eros dolor, non volutpat metus sagittis sit amet. Quisque dignissim tortor quis sem aliquet varius. Nam nec condimentum lacus, sit amet iaculis metus.

Nunc placerat dignissim felis, ac tristique dui cursus eu. Nam suscipit condimentum sem, vitae auctor turpis scelerisque tempus. Mauris hendrerit ligula dictum, convallis purus ut, semper purus. Ut imperdiet erat a mauris convallis fringilla. Nunc convallis nunc ipsum, vel posuere magna imperdiet sed. In hac habitasse platea dictumst. Pellentesque nec urna at nibh consectetur sollicitudin. In hac habitasse platea d', user_id: user.id)
Post.create(title: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', body: 'tLorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas lobortis bibendum dolor, in commodo risus ultrices id. Vestibulum luctus dictum tortor, sit amet pretium ligula facilisis eu. Nullam interdum neque sit amet mi ornare, in scelerisque nibh ultrices. Donec eleifend eros ac ipsum commodo, et consectetur dui cursus. Integer in volutpat metus. Maecenas fermentum et ante sed luctus. Mauris felis diam, blandit at turpis sit amet, lacinia ultricies ex. Nunc massa quam, consectetur ac imperdiet nec, cursus ac neque. Nunc bibendum, nisi vitae convallis venenatis, felis est accumsan risus, vel gravida orci nibh vel purus. Vestibulum tempus vitae nisl eget vestibulum. Suspendisse quis est eu est placerat posuere vitae ac ante. Curabitur eu elit ligula. Curabitur ultricies interdum mauris sodales cursus. Vestibulum auctor velit et sapien vulputate consectetur.

Integer non interdum massa. In vitae vulputate dui. Etiam faucibus, sem et malesuada efficitur, tellus ipsum eleifend tellus, in dictum ligula dui ut lorem. Proin ultrices sit amet quam sed accumsan. Quisque vitae velit nec diam semper aliquet. In interdum odio id dui egestas, ac accumsan nulla maximus. Duis vel ligula vitae mi maximus pulvinar id ut arcu. Donec metus tellus, feugiat at felis in, interdum pulvinar ante. Proin eu laoreet lacus. Donec ut tempor arcu. Ut at tellus finibus est tempor rhoncus in tristique ex. Integer in turpis ut turpis egestas malesuada a ut mauris. Aliquam mattis nibh odio, nec dignissim quam pharetra sagittis.

Vestibulum lacinia non lacus nec consequat. Maecenas tempor varius massa ullamcorper varius. Phasellus lobortis in lectus rhoncus rutrum. Maecenas imperdiet dapibus lorem, eu sodales magna. Fusce non placerat mi, eu consequat odio. Ut porta ultrices consectetur. Praesent nunc mauris, iaculis eget lorem ut, mollis feugiat enim. Nunc commodo vitae ante a congue. Integer bibendum luctus lacus eu sollicitudin. Curabitur consequat justo ut nisl feugiat ultrices.

Suspendisse consequat lacus id nisl viverra, vitae ultricies lacus lacinia. Proin aliquam aliquet ipsum, vel tristique nisl rutrum euismod. Sed blandit tellus sit amet lorem viverra hendrerit. Etiam vel ultricies diam. Sed non nunc dapibus turpis ultricies tristique eget vitae enim. Nullam lobortis eros augue. Suspendisse enim ligula, consequat eu tincidunt non, aliquet et ligula. Praesent vestibulum commodo est ut ultrices. Curabitur vel mattis mi. Integer laoreet tempor sem, nec blandit purus mattis id. Praesent tristique lectus gravida, molestie ante vel, congue lectus. Etiam tempus facilisis erat, et semper quam ultricies at. Nunc accumsan eros dolor, non volutpat metus sagittis sit amet. Quisque dignissim tortor quis sem aliquet varius. Nam nec condimentum lacus, sit amet iaculis metus.

Nunc placerat dignissim felis, ac tristique dui cursus eu. Nam suscipit condimentum sem, vitae auctor turpis scelerisque tempus. Mauris hendrerit ligula dictum, convallis purus ut, semper purus. Ut imperdiet erat a mauris convallis fringilla. Nunc convallis nunc ipsum, vel posuere magna imperdiet sed. In hac habitasse platea dictumst. Pellentesque nec urna at nibh consectetur sollicitudin. In hac habitasse platea d', user_id: user.id)
Post.create(title: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas lobortis bibendum dolor, in commodo risus ultrices id. Vestibulum luctus dictum tortor, sit amet pretium ligula facilisis eu. Nullam interdum neque sit amet mi ornare, in scelerisque nibh ultrices. Donec eleifend eros ac ipsum commodo, et consectetur dui cursus. Integer in volutpat metus. Maecenas fermentum et ante sed luctus. Mauris felis diam, blandit at turpis sit amet, lacinia ultricies ex. Nunc massa quam, consectetur ac imperdiet nec, cursus ac neque. Nunc bibendum, nisi vitae convallis venenatis, felis est accumsan risus, vel gravida orci nibh vel purus. Vestibulum tempus vitae nisl eget vestibulum. Suspendisse quis est eu est placerat posuere vitae ac ante. Curabitur eu elit ligula. Curabitur ultricies interdum mauris sodales cursus. Vestibulum auctor velit et sapien vulputate consectetur.

Integer non interdum massa. In vitae vulputate dui. Etiam faucibus, sem et malesuada efficitur, tellus ipsum eleifend tellus, in dictum ligula dui ut lorem. Proin ultrices sit amet quam sed accumsan. Quisque vitae velit nec diam semper aliquet. In interdum odio id dui egestas, ac accumsan nulla maximus. Duis vel ligula vitae mi maximus pulvinar id ut arcu. Donec metus tellus, feugiat at felis in, interdum pulvinar ante. Proin eu laoreet lacus. Donec ut tempor arcu. Ut at tellus finibus est tempor rhoncus in tristique ex. Integer in turpis ut turpis egestas malesuada a ut mauris. Aliquam mattis nibh odio, nec dignissim quam pharetra sagittis.

Vestibulum lacinia non lacus nec consequat. Maecenas tempor varius massa ullamcorper varius. Phasellus lobortis in lectus rhoncus rutrum. Maecenas imperdiet dapibus lorem, eu sodales magna. Fusce non placerat mi, eu consequat odio. Ut porta ultrices consectetur. Praesent nunc mauris, iaculis eget lorem ut, mollis feugiat enim. Nunc commodo vitae ante a congue. Integer bibendum luctus lacus eu sollicitudin. Curabitur consequat justo ut nisl feugiat ultrices.

Suspendisse consequat lacus id nisl viverra, vitae ultricies lacus lacinia. Proin aliquam aliquet ipsum, vel tristique nisl rutrum euismod. Sed blandit tellus sit amet lorem viverra hendrerit. Etiam vel ultricies diam. Sed non nunc dapibus turpis ultricies tristique eget vitae enim. Nullam lobortis eros augue. Suspendisse enim ligula, consequat eu tincidunt non, aliquet et ligula. Praesent vestibulum commodo est ut ultrices. Curabitur vel mattis mi. Integer laoreet tempor sem, nec blandit purus mattis id. Praesent tristique lectus gravida, molestie ante vel, congue lectus. Etiam tempus facilisis erat, et semper quam ultricies at. Nunc accumsan eros dolor, non volutpat metus sagittis sit amet. Quisque dignissim tortor quis sem aliquet varius. Nam nec condimentum lacus, sit amet iaculis metus.

Nunc placerat dignissim felis, ac tristique dui cursus eu. Nam suscipit condimentum sem, vitae auctor turpis scelerisque tempus. Mauris hendrerit ligula dictum, convallis purus ut, semper purus. Ut imperdiet erat a mauris convallis fringilla. Nunc convallis nunc ipsum, vel posuere magna imperdiet sed. In hac habitasse platea dictumst. Pellentesque nec urna at nibh consectetur sollicitudin. In hac habitasse platea d', user_id: user.id)
Post.create(title: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', body: 'tLorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas lobortis bibendum dolor, in commodo risus ultrices id. Vestibulum luctus dictum tortor, sit amet pretium ligula facilisis eu. Nullam interdum neque sit amet mi ornare, in scelerisque nibh ultrices. Donec eleifend eros ac ipsum commodo, et consectetur dui cursus. Integer in volutpat metus. Maecenas fermentum et ante sed luctus. Mauris felis diam, blandit at turpis sit amet, lacinia ultricies ex. Nunc massa quam, consectetur ac imperdiet nec, cursus ac neque. Nunc bibendum, nisi vitae convallis venenatis, felis est accumsan risus, vel gravida orci nibh vel purus. Vestibulum tempus vitae nisl eget vestibulum. Suspendisse quis est eu est placerat posuere vitae ac ante. Curabitur eu elit ligula. Curabitur ultricies interdum mauris sodales cursus. Vestibulum auctor velit et sapien vulputate consectetur.

Integer non interdum massa. In vitae vulputate dui. Etiam faucibus, sem et malesuada efficitur, tellus ipsum eleifend tellus, in dictum ligula dui ut lorem. Proin ultrices sit amet quam sed accumsan. Quisque vitae velit nec diam semper aliquet. In interdum odio id dui egestas, ac accumsan nulla maximus. Duis vel ligula vitae mi maximus pulvinar id ut arcu. Donec metus tellus, feugiat at felis in, interdum pulvinar ante. Proin eu laoreet lacus. Donec ut tempor arcu. Ut at tellus finibus est tempor rhoncus in tristique ex. Integer in turpis ut turpis egestas malesuada a ut mauris. Aliquam mattis nibh odio, nec dignissim quam pharetra sagittis.

Vestibulum lacinia non lacus nec consequat. Maecenas tempor varius massa ullamcorper varius. Phasellus lobortis in lectus rhoncus rutrum. Maecenas imperdiet dapibus lorem, eu sodales magna. Fusce non placerat mi, eu consequat odio. Ut porta ultrices consectetur. Praesent nunc mauris, iaculis eget lorem ut, mollis feugiat enim. Nunc commodo vitae ante a congue. Integer bibendum luctus lacus eu sollicitudin. Curabitur consequat justo ut nisl feugiat ultrices.

Suspendisse consequat lacus id nisl viverra, vitae ultricies lacus lacinia. Proin aliquam aliquet ipsum, vel tristique nisl rutrum euismod. Sed blandit tellus sit amet lorem viverra hendrerit. Etiam vel ultricies diam. Sed non nunc dapibus turpis ultricies tristique eget vitae enim. Nullam lobortis eros augue. Suspendisse enim ligula, consequat eu tincidunt non, aliquet et ligula. Praesent vestibulum commodo est ut ultrices. Curabitur vel mattis mi. Integer laoreet tempor sem, nec blandit purus mattis id. Praesent tristique lectus gravida, molestie ante vel, congue lectus. Etiam tempus facilisis erat, et semper quam ultricies at. Nunc accumsan eros dolor, non volutpat metus sagittis sit amet. Quisque dignissim tortor quis sem aliquet varius. Nam nec condimentum lacus, sit amet iaculis metus.

Nunc placerat dignissim felis, ac tristique dui cursus eu. Nam suscipit condimentum sem, vitae auctor turpis scelerisque tempus. Mauris hendrerit ligula dictum, convallis purus ut, semper purus. Ut imperdiet erat a mauris convallis fringilla. Nunc convallis nunc ipsum, vel posuere magna imperdiet sed. In hac habitasse platea dictumst. Pellentesque nec urna at nibh consectetur sollicitudin. In hac habitasse platea d', user_id: user.id)

posts = Post.all

posts.each do |post|
  Comment.create(body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas lobortis bibendum dolor, in commodo risus ultrices id. Vestibulum luctus dictum tortor, sit amet pretium ligula facilisis eu. Nullam interdum neque sit amet mi ornare, in scelerisque nibh ultrices. Donec eleifend eros ac ipsum commodo, et consectetur dui cursus. Integer in volutpat metus. Maecenas fermentum et ante sed luctus. Mauris felis diam, blandit at turpis sit amet, lacinia ultricies ex. Nunc massa quam, consectetur ac imperdiet nec, cursus ac neque. Nunc bibendum, nisi vitae convallis venenatis, felis est accumsan risus, vel gravida orci nibh vel purus. Vestibulum tempus vitae nisl eget vestibulum. Suspendisse quis est eu est placerat posuere vitae ac ante. Curabitur eu elit ligula. Curabitur ultricies interdum mauris sodales cursus. Vestibulum auctor velit et sapien vulputate consectetur.

Integer non interdum massa. In vitae vulputate dui. Etiam faucibus, sem et malesuada efficitur, tellus ipsum eleifend tellus, in dictum ligula dui ut lorem. Proin ultrices sit amet quam sed accumsan. Quisque vitae velit nec diam semper aliquet. In interdum odio id dui egestas, ac accumsan nulla maximus. Duis vel ligula vitae mi maximus pulvinar id ut arcu. Donec metus tellus, feugiat at felis in, interdum pulvinar ante. Proin eu laoreet lacus. Donec ut tempor arcu. Ut at tellus finibus est tempor rhoncus in tristique ex. Integer in turpis ut turpis egestas malesuada a ut mauris. Aliquam mattis nibh odio, nec dignissim quam pharetra sagittis.

Vestibulum lacinia non lacus nec consequat. Maecenas tempor varius massa ullamcorper varius. Phasellus lobortis in lectus rhoncus rutrum. Maecenas imperdiet dapibus lorem, eu sodales magna. Fusce non placerat mi, eu consequat odio. Ut porta ultrices consectetur. Praesent nunc mauris, iaculis eget lorem ut, mollis feugiat enim. Nunc commodo vitae ante a congue. Integer bibendum luctus lacus eu sollicitudin. Curabitur consequat justo ut nisl feugiat ultrices.

Suspendisse consequat lacus id nisl viverra, vitae ultricies lacus lacinia. Proin aliquam aliquet ipsum, vel tristique nisl rutrum euismod. Sed blandit tellus sit amet lorem viverra hendrerit. Etiam vel ultricies diam. Sed non nunc dapibus turpis ultricies tristique eget vitae enim. Nullam lobortis eros augue. Suspendisse enim ligula, consequat eu tincidunt non, aliquet et ligula. Praesent vestibulum commodo est ut ultrices. Curabitur vel mattis mi. Integer laoreet tempor sem, nec blandit purus mattis id. Praesent tristique lectus gravida, molestie ante vel, congue lectus. Etiam tempus facilisis erat, et semper quam ultricies at. Nunc accumsan eros dolor, non volutpat metus sagittis sit amet. Quisque dignissim tortor quis sem aliquet varius. Nam nec condimentum lacus, sit amet iaculis metus.

Nunc placerat dignissim felis, ac tristique dui cursus eu. Nam suscipit condimentum sem, vitae auctor turpis scelerisque tempus. Mauris hendrerit ligula dictum, convallis purus ut, semper purus. Ut imperdiet erat a mauris convallis fringilla. Nunc convallis nunc ipsum, vel posuere magna imperdiet sed. In hac habitasse platea dictumst. Pellentesque nec urna at nibh consectetur sollicitudin. In hac habitasse platea ds', user_id: user.id, post_id: post.id)
  Comment.create(body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas lobortis bibendum dolor, in commodo risus ultrices id. Vestibulum luctus dictum tortor, sit amet pretium ligula facilisis eu. Nullam interdum neque sit amet mi ornare, in scelerisque nibh ultrices. Donec eleifend eros ac ipsum commodo, et consectetur dui cursus. Integer in volutpat metus. Maecenas fermentum et ante sed luctus. Mauris felis diam, blandit at turpis sit amet, lacinia ultricies ex. Nunc massa quam, consectetur ac imperdiet nec, cursus ac neque. Nunc bibendum, nisi vitae convallis venenatis, felis est accumsan risus, vel gravida orci nibh vel purus. Vestibulum tempus vitae nisl eget vestibulum. Suspendisse quis est eu est placerat posuere vitae ac ante. Curabitur eu elit ligula. Curabitur ultricies interdum mauris sodales cursus. Vestibulum auctor velit et sapien vulputate consectetur.

Integer non interdum massa. In vitae vulputate dui. Etiam faucibus, sem et malesuada efficitur, tellus ipsum eleifend tellus, in dictum ligula dui ut lorem. Proin ultrices sit amet quam sed accumsan. Quisque vitae velit nec diam semper aliquet. In interdum odio id dui egestas, ac accumsan nulla maximus. Duis vel ligula vitae mi maximus pulvinar id ut arcu. Donec metus tellus, feugiat at felis in, interdum pulvinar ante. Proin eu laoreet lacus. Donec ut tempor arcu. Ut at tellus finibus est tempor rhoncus in tristique ex. Integer in turpis ut turpis egestas malesuada a ut mauris. Aliquam mattis nibh odio, nec dignissim quam pharetra sagittis.

Vestibulum lacinia non lacus nec consequat. Maecenas tempor varius massa ullamcorper varius. Phasellus lobortis in lectus rhoncus rutrum. Maecenas imperdiet dapibus lorem, eu sodales magna. Fusce non placerat mi, eu consequat odio. Ut porta ultrices consectetur. Praesent nunc mauris, iaculis eget lorem ut, mollis feugiat enim. Nunc commodo vitae ante a congue. Integer bibendum luctus lacus eu sollicitudin. Curabitur consequat justo ut nisl feugiat ultrices.

Suspendisse consequat lacus id nisl viverra, vitae ultricies lacus lacinia. Proin aliquam aliquet ipsum, vel tristique nisl rutrum euismod. Sed blandit tellus sit amet lorem viverra hendrerit. Etiam vel ultricies diam. Sed non nunc dapibus turpis ultricies tristique eget vitae enim. Nullam lobortis eros augue. Suspendisse enim ligula, consequat eu tincidunt non, aliquet et ligula. Praesent vestibulum commodo est ut ultrices. Curabitur vel mattis mi. Integer laoreet tempor sem, nec blandit purus mattis id. Praesent tristique lectus gravida, molestie ante vel, congue lectus. Etiam tempus facilisis erat, et semper quam ultricies at. Nunc accumsan eros dolor, non volutpat metus sagittis sit amet. Quisque dignissim tortor quis sem aliquet varius. Nam nec condimentum lacus, sit amet iaculis metus.

Nunc placerat dignissim felis, ac tristique dui cursus eu. Nam suscipit condimentum sem, vitae auctor turpis scelerisque tempus. Mauris hendrerit ligula dictum, convallis purus ut, semper purus. Ut imperdiet erat a mauris convallis fringilla. Nunc convallis nunc ipsum, vel posuere magna imperdiet sed. In hac habitasse platea dictumst. Pellentesque nec urna at nibh consectetur sollicitudin. In hac habitasse platea d', user_id: user.id, post_id: post.id)
  Comment.create(body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas lobortis bibendum dolor, in commodo risus ultrices id. Vestibulum luctus dictum tortor, sit amet pretium ligula facilisis eu. Nullam interdum neque sit amet mi ornare, in scelerisque nibh ultrices. Donec eleifend eros ac ipsum commodo, et consectetur dui cursus. Integer in volutpat metus. Maecenas fermentum et ante sed luctus. Mauris felis diam, blandit at turpis sit amet, lacinia ultricies ex. Nunc massa quam, consectetur ac imperdiet nec, cursus ac neque. Nunc bibendum, nisi vitae convallis venenatis, felis est accumsan risus, vel gravida orci nibh vel purus. Vestibulum tempus vitae nisl eget vestibulum. Suspendisse quis est eu est placerat posuere vitae ac ante. Curabitur eu elit ligula. Curabitur ultricies interdum mauris sodales cursus. Vestibulum auctor velit et sapien vulputate consectetur.

Integer non interdum massa. In vitae vulputate dui. Etiam faucibus, sem et malesuada efficitur, tellus ipsum eleifend tellus, in dictum ligula dui ut lorem. Proin ultrices sit amet quam sed accumsan. Quisque vitae velit nec diam semper aliquet. In interdum odio id dui egestas, ac accumsan nulla maximus. Duis vel ligula vitae mi maximus pulvinar id ut arcu. Donec metus tellus, feugiat at felis in, interdum pulvinar ante. Proin eu laoreet lacus. Donec ut tempor arcu. Ut at tellus finibus est tempor rhoncus in tristique ex. Integer in turpis ut turpis egestas malesuada a ut mauris. Aliquam mattis nibh odio, nec dignissim quam pharetra sagittis.

Vestibulum lacinia non lacus nec consequat. Maecenas tempor varius massa ullamcorper varius. Phasellus lobortis in lectus rhoncus rutrum. Maecenas imperdiet dapibus lorem, eu sodales magna. Fusce non placerat mi, eu consequat odio. Ut porta ultrices consectetur. Praesent nunc mauris, iaculis eget lorem ut, mollis feugiat enim. Nunc commodo vitae ante a congue. Integer bibendum luctus lacus eu sollicitudin. Curabitur consequat justo ut nisl feugiat ultrices.

Suspendisse consequat lacus id nisl viverra, vitae ultricies lacus lacinia. Proin aliquam aliquet ipsum, vel tristique nisl rutrum euismod. Sed blandit tellus sit amet lorem viverra hendrerit. Etiam vel ultricies diam. Sed non nunc dapibus turpis ultricies tristique eget vitae enim. Nullam lobortis eros augue. Suspendisse enim ligula, consequat eu tincidunt non, aliquet et ligula. Praesent vestibulum commodo est ut ultrices. Curabitur vel mattis mi. Integer laoreet tempor sem, nec blandit purus mattis id. Praesent tristique lectus gravida, molestie ante vel, congue lectus. Etiam tempus facilisis erat, et semper quam ultricies at. Nunc accumsan eros dolor, non volutpat metus sagittis sit amet. Quisque dignissim tortor quis sem aliquet varius. Nam nec condimentum lacus, sit amet iaculis metus.

Nunc placerat dignissim felis, ac tristique dui cursus eu. Nam suscipit condimentum sem, vitae auctor turpis scelerisque tempus. Mauris hendrerit ligula dictum, convallis purus ut, semper purus. Ut imperdiet erat a mauris convallis fringilla. Nunc convallis nunc ipsum, vel posuere magna imperdiet sed. In hac habitasse platea dictumst. Pellentesque nec urna at nibh consectetur sollicitudin. In hac habitasse platea d', user_id: user.id, post_id: post.id)
  Comment.create(body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas lobortis bibendum dolor, in commodo risus ultrices id. Vestibulum luctus dictum tortor, sit amet pretium ligula facilisis eu. Nullam interdum neque sit amet mi ornare, in scelerisque nibh ultrices. Donec eleifend eros ac ipsum commodo, et consectetur dui cursus. Integer in volutpat metus. Maecenas fermentum et ante sed luctus. Mauris felis diam, blandit at turpis sit amet, lacinia ultricies ex. Nunc massa quam, consectetur ac imperdiet nec, cursus ac neque. Nunc bibendum, nisi vitae convallis venenatis, felis est accumsan risus, vel gravida orci nibh vel purus. Vestibulum tempus vitae nisl eget vestibulum. Suspendisse quis est eu est placerat posuere vitae ac ante. Curabitur eu elit ligula. Curabitur ultricies interdum mauris sodales cursus. Vestibulum auctor velit et sapien vulputate consectetur.

Integer non interdum massa. In vitae vulputate dui. Etiam faucibus, sem et malesuada efficitur, tellus ipsum eleifend tellus, in dictum ligula dui ut lorem. Proin ultrices sit amet quam sed accumsan. Quisque vitae velit nec diam semper aliquet. In interdum odio id dui egestas, ac accumsan nulla maximus. Duis vel ligula vitae mi maximus pulvinar id ut arcu. Donec metus tellus, feugiat at felis in, interdum pulvinar ante. Proin eu laoreet lacus. Donec ut tempor arcu. Ut at tellus finibus est tempor rhoncus in tristique ex. Integer in turpis ut turpis egestas malesuada a ut mauris. Aliquam mattis nibh odio, nec dignissim quam pharetra sagittis.

Vestibulum lacinia non lacus nec consequat. Maecenas tempor varius massa ullamcorper varius. Phasellus lobortis in lectus rhoncus rutrum. Maecenas imperdiet dapibus lorem, eu sodales magna. Fusce non placerat mi, eu consequat odio. Ut porta ultrices consectetur. Praesent nunc mauris, iaculis eget lorem ut, mollis feugiat enim. Nunc commodo vitae ante a congue. Integer bibendum luctus lacus eu sollicitudin. Curabitur consequat justo ut nisl feugiat ultrices.

Suspendisse consequat lacus id nisl viverra, vitae ultricies lacus lacinia. Proin aliquam aliquet ipsum, vel tristique nisl rutrum euismod. Sed blandit tellus sit amet lorem viverra hendrerit. Etiam vel ultricies diam. Sed non nunc dapibus turpis ultricies tristique eget vitae enim. Nullam lobortis eros augue. Suspendisse enim ligula, consequat eu tincidunt non, aliquet et ligula. Praesent vestibulum commodo est ut ultrices. Curabitur vel mattis mi. Integer laoreet tempor sem, nec blandit purus mattis id. Praesent tristique lectus gravida, molestie ante vel, congue lectus. Etiam tempus facilisis erat, et semper quam ultricies at. Nunc accumsan eros dolor, non volutpat metus sagittis sit amet. Quisque dignissim tortor quis sem aliquet varius. Nam nec condimentum lacus, sit amet iaculis metus.

Nunc placerat dignissim felis, ac tristique dui cursus eu. Nam suscipit condimentum sem, vitae auctor turpis scelerisque tempus. Mauris hendrerit ligula dictum, convallis purus ut, semper purus. Ut imperdiet erat a mauris convallis fringilla. Nunc convallis nunc ipsum, vel posuere magna imperdiet sed. In hac habitasse platea dictumst. Pellentesque nec urna at nibh consectetur sollicitudin. In hac habitasse platea d', user_id: user.id, post_id: post.id)
end
